[[constraint]]
	name = "github.com/hajimehoshi/ebiten"
	# version = "^1.5.1"
	branch = "master"
	# revision = ""

[[constraint]]
	name = "github.com/Bredgren/geo"
	# version = "v1.0.0-beta2"
	branch = "master"

[[constraint]]
	name = "github.com/solovev/gopsd"
	revision = "324149dd34bc90d56963669f7a288d96b7d9ba10"
